import type { PresetItem } from '../types';

export const PRESETS: PresetItem[] = [
  {
    id: 'all',
    name: 'Все протоколы',
    desc: 'Полный срез',
    icon: 'layers',
    services: [],
    country: 'all',
    proto: 'all',
    maxPing: 0,
  },
  {
    id: 'anti-tspu',
    name: 'Анти-ТСПУ (РКН)',
    desc: 'VLESS Reality',
    icon: 'shield',
    services: [],
    country: 'all',
    proto: 'reality',
    maxPing: 0,
  },
  {
    id: 'ai',
    name: 'AI & Нейросети',
    desc: 'ChatGPT, Claude, Gemini',
    icon: 'sparkles',
    services: ['chatgpt', 'claude', 'gemini'],
    country: 'all',
    proto: 'all',
    maxPing: 0,
  },
  {
    id: 'youtube',
    name: 'YouTube 4K',
    desc: 'Hysteria 2 + Reality',
    icon: 'tv',
    services: ['youtube', 'discord'],
    country: 'all',
    proto: 'all',
    maxPing: 0,
  },
];

export const KNOWN_COUNTRIES: Record<string, string> = {
  de: 'Германия',
  nl: 'Нидерланды',
  fi: 'Финляндия',
  se: 'Швеция',
  kz: 'Казахстан',
  tr: 'Турция',
  ru: 'Россия',
  us: 'США',
  gb: 'Великобритания',
  fr: 'Франция',
  sg: 'Сингапур',
  jp: 'Япония',
  hk: 'Гонконг',
  kr: 'Южная Корея',
  ca: 'Канада',
  au: 'Австралия',
  pl: 'Польша',
  at: 'Австрия',
  ch: 'Швейцария',
  it: 'Италия',
  es: 'Испания',
  cz: 'Чехия',
  no: 'Норвегия',
  dk: 'Дания',
  ro: 'Румыния',
  bg: 'Болгария',
  ua: 'Украина',
  md: 'Молдова',
  ge: 'Грузия',
  am: 'Армения',
  uz: 'Узбекистан',
  ae: 'ОАЭ',
  il: 'Израиль',
  in: 'Индия',
  br: 'Бразилия',
  id: 'Индонезия',
  th: 'Таиланд',
  my: 'Малайзия',
  vn: 'Вьетнам',
  tw: 'Тайвань',
  ee: 'Эстония',
  lv: 'Латвия',
  lt: 'Литва',
  rs: 'Сербия',
  gr: 'Греция',
  pt: 'Португалия',
  hu: 'Венгрия',
  ie: 'Ирландия',
  nz: 'Новая Зеландия',
  za: 'ЮАР',
  mx: 'Мексика',
  ar: 'Аргентина',
  cl: 'Чили',
  co: 'Колумбия',
  is: 'Исландия',
  cy: 'Кипр',
  mt: 'Мальта',
};

export const KNOWN_PROTOCOLS: Record<string, string> = {
  reality: 'VLESS Reality',
  hy2: 'Hysteria 2',
  trojan: 'Trojan TLS',
  ss: 'Shadowsocks',
  vless: 'VLESS',
  vmess: 'VMess',
  tuic: 'TUIC',
};
